language: node_js

node_js: "8.9"

jobs:
  include:
    - stage: pre-build
      script: npm install -g @angular/cli

    - stage: test
      script: npm test

    - stage: build
      script: ng build --prod