language: node_js

node_js: "8.9"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

jobs:
  include:

    - stage: test
      script: export CHROME_BIN=chromium-browser
      script: export DISPLAY=:99.0
      script: sh -e /etc/init.d/xvfb start
      script: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      script: npm test

    - stage: build
      script: ng build --prod