language: node_js

node_js: "8.9"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

jobs:
  include:

    - stage: test
      script: 
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - ng tests --watch=false

    - stage: build
      script: ng build --prod