version: 0.2

env:
    variables:
        S3_BUCKET: "rmsweb.revature.com"
        BUILD_ENV : "cloud-dev"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --configuration=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    discard-paths: yes
